// Blood Request Lifecycle Statuses
export const REQUEST_STATUS = {
  SUBMITTED: 'Submitted',
  PENDING_VERIFICATION: 'Pending Verification',
  VERIFIED: 'Verified',
  SEARCHING: 'Searching for Donors',
  RESPONSE_RECEIVED: 'Donor Response Received',
  FULFILLED: 'Fulfilled',
  CANCELLED: 'Cancelled',
  EXPIRED: 'Expired'
};

// Allowed State Transitions
export const VALID_STATUS_TRANSITIONS = {
  [REQUEST_STATUS.SUBMITTED]: [
    REQUEST_STATUS.PENDING_VERIFICATION,
    REQUEST_STATUS.VERIFIED,
    REQUEST_STATUS.CANCELLED
  ],
  [REQUEST_STATUS.PENDING_VERIFICATION]: [
    REQUEST_STATUS.VERIFIED,
    REQUEST_STATUS.CANCELLED
  ],
  [REQUEST_STATUS.VERIFIED]: [
    REQUEST_STATUS.SEARCHING,
    REQUEST_STATUS.CANCELLED
  ],
  [REQUEST_STATUS.SEARCHING]: [
    REQUEST_STATUS.RESPONSE_RECEIVED,
    REQUEST_STATUS.FULFILLED,
    REQUEST_STATUS.CANCELLED,
    REQUEST_STATUS.EXPIRED
  ],
  [REQUEST_STATUS.RESPONSE_RECEIVED]: [
    REQUEST_STATUS.SEARCHING,
    REQUEST_STATUS.FULFILLED,
    REQUEST_STATUS.CANCELLED,
    REQUEST_STATUS.EXPIRED
  ],
  [REQUEST_STATUS.FULFILLED]: [],
  [REQUEST_STATUS.CANCELLED]: [],
  [REQUEST_STATUS.EXPIRED]: []
};

// Donor Match / Response status
export const DONOR_MATCH_STATUS = {
  IDENTIFIED: 'IDENTIFIED',
  CONTACTED: 'CONTACTED',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  TIMEOUT: 'TIMEOUT'
};

export const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED'
};
